apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-app
type: Opaque
stringData:
  mysql-root-password: Root1234
  mysql-database: studentdb
  mysql-user: studentuser
  mysql-password: Student1234
